# Data Encoding

(1) Nominal/OHE Encoding

(2) Label and Ordinal Encoding

(3) Target Guided Ordinal Encoding

In [31]:
# Converting categorical values into numerical values because model only understand numerical values.

### Nominal or One Hot Encoding

This technique is used to represent categorical data as numerical data.

disdvantages  - we have 100 categories it will create 100 new features
             
              - Sparse matrix (1s,0s) -> cause overfitting

In [32]:
import pandas as pd 
from sklearn.preprocessing import OneHotEncoder

In [33]:
## Create a simple dataframe
df= pd.DataFrame({
        'color' : ['red','blue','green','green','red','blue']
    })

In [34]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [35]:
## Create an instance of OneHotencoder
encoder= OneHotEncoder()

In [36]:
#Perform fit and tranform 
encoded=encoder.fit_transform(df[['color']]).toarray()

In [37]:
import pandas as pd # Convert into numerical format
encoder_df = pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [38]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [39]:
encoder.transform([['blue']]).toarray() #transform new data

c:\Users\Manis\OneDrive\vs COdE Python\Data-Science-Journey\.venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [40]:
pd.concat([df,encoder_df],axis=1) #merge with original data

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

In [41]:
import seaborn as sns
sns.load_dataset('tips')

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

### Label Encoding

label encoding involves assigning a unique numerical label to each category in the variable.

labels are assigned in alphabetical order

In [42]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [43]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder = LabelEncoder()

In [ ]:
lbl_encoder.fit_transform(df[['color']])
# blue -> 0
# green -> 1
# red -> 2

c:\Users\Manis\OneDrive\vs COdE Python\Data-Science-Journey\.venv\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2, 0])

In [48]:
lbl_encoder.transform([['red']])

c:\Users\Manis\OneDrive\vs COdE Python\Data-Science-Journey\.venv\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

In [46]:
lbl_encoder.transform([['blue']])

c:\Users\Manis\OneDrive\vs COdE Python\Data-Science-Journey\.venv\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([0])

In [30]:
lbl_encoder.transform([['green']])

c:\Users\Manis\OneDrive\vs COdE Python\Data-Science-Journey\.venv\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([1])

#### Problem with label encoding : 

When we are assigning unique labels for red,blue,green. red has got 2 so model will think red may have higher values then blue and green but that should not happen because this are nominal values. 
But if we need to assign values based on rank we will use

### Ordinal Encoding

It is used to encode categorical data in ranks. In this technique, each category is assigned a numerical value based on its position in the order. For example, if we have categorical variable "education level" with four possible values 

High school : 1

College : 2

Graduate : 3

post-graduate : 4

In [49]:
from sklearn.preprocessing import OrdinalEncoder

In [50]:
df = pd.DataFrame({
    'size': ['small','medium', 'large', 'medium', 'small', 'large']
})

In [51]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [53]:
#create a instance of OrdinalEncoder then perform fit_tranform
encoder = OrdinalEncoder(categories=[['small','medium','large']])

In [55]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [57]:
encoder.transform([['small']])

c:\Users\Manis\OneDrive\vs COdE Python\Data-Science-Journey\.venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])

### Target Guided Ordinal Encoding
It is a technique used to encode categorical variables based on thier relationship with the target variable. This encoding technique is useful when we have a categorical variable with large number of unique categories, and we want to ise this variable as feature in machine learning model.

In This Encoding, we replace eacvh category in the categorical variable with numerical value based on mean and median of the target variable for that category.

In [59]:
df = pd.DataFrame({
    'city':['New york','Londan','Paris','Tokyo','New york','Paris'],
    'price' : [200,150,300,250,180,320]
})
df

       city  price
0  New york    200
1    Londan    150
2     Paris    300
3     Tokyo    250
4  New york    180
5     Paris    320

In [64]:
mean_price=df.groupby('city')['price'].mean().to_dict()
mean_price

{'Londan': 150.0, 'New york': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [65]:
df['city_encoded']=df['city'].map(mean_price)

In [68]:
df[['city','price','city_encoded']]

       city  price  city_encoded
0  New york    200         190.0
1    Londan    150         150.0
2     Paris    300         310.0
3     Tokyo    250         250.0
4  New york    180         190.0
5     Paris    320         310.0

In [ ]:
# import seaborn as sns
# sns.load_datasets('tips')